version: '3'

services:
  app:
    build:
        context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s docker-entrypoint.sh
    command: node index
    restart: always
    networks:
      - myapp-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    expose:
      - "3000"
    depends_on:
      - db
  db:
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: nodedb
    networks:
      - myapp-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kelvinramires/nginx:node-prod
    container_name: nginx
    networks:
      - myapp-network
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  myapp-network:
    driver: bridge
volumes:
  mysql:
  node:
