version: '3'

services:
  app:
    build:
        context: ./node
        dockerfile: Dockerfile
    container_name: app
    networks:
      - myapp-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=teste
    networks:
      - myapp-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kelvinramires/nginx:node-prod
    container_name: nginx
    networks:
      - myapp-network
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  myapp-network:
    driver: bridge

